// ------ This code is generated by a code generator.  Do not edit. ------

// noinspection JSUnusedLocalSymbols
module.exports = {
    Identifier: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        assigner: async (parent, args, context, info) => {
            return await context.dataApi.findResourceByReference(
                parent,
                args,
                context,
                info,
                parent.assigner);
        },
    }
};

