import os
from pathlib import Path
import shutil


def main() -> int:
    resources = ['Account', 'ActivityDefinition', 'AdverseEvent', 'AllergyIntolerance', 'Appointment',
                 'AppointmentResponse', 'AuditEvent', 'Basic', 'Binary', 'BodyStructure',
                 'Bundle', 'CapabilityStatement', 'CarePlan', 'CareTeam', 'ChargeItem',
                 'ChargeItemDefinition', 'Claim', 'ClaimResponse', 'ClinicalImpression', 'CodeSystem', 'Communication',
                 'CommunicationRequest', 'CompartmentDefinition', 'Composition', 'ConceptMap', 'Condition', 'Consent',
                 'Contract', 'Coverage', 'CoverageEligibilityRequest', 'CoverageEligibilityResponse', 'DetectedIssue',
                 'Device', 'DeviceDefinition', 'DeviceMetric', 'DeviceRequest', 'DeviceUseStatement',
                 'DiagnosticReport', 'DocumentManifest', 'DocumentReference', 'EffectEvidenceSynthesis', 'Encounter',
                 'Endpoint', 'EnrollmentRequest', 'EnrollmentResponse', 'EpisodeOfCare', 'EventDefinition',
                 'ExampleScenario', 'ExplanationOfBenefit', 'FamilyMemberHistory', 'Flag', 'Goal',
                 'GraphDefinition', 'Group', 'GuidanceResponse', 'HealthcareService', 'ImagingStudy', 'Immunization',
                 'ImmunizationEvaluation', 'ImmunizationRecommendation', 'ImplementationGuide', 'InsurancePlan',
                 'Invoice', 'Library', 'Linkage', 'List', 'Location', 'Measure', 'MeasureReport', 'Media', 'Medication',
                 'MedicationAdministration', 'MedicationDispense', 'MedicationKnowledge', 'MedicationRequest',
                 'MedicationStatement', 'MedicinalProduct', 'MedicinalProductAuthorization',
                 'MedicinalProductContraindication', 'MedicinalProductIndication',
                 'MedicinalProductPackaged',
                 'MedicinalProductPharmaceutical', 'MessageDefinition',
                 'MessageHeader', 'MolecularSequence', 'NamingSystem', 'NutritionOrder', 'Observation',
                 'OperationDefinition', 'Organization',
                 'OrganizationAffiliation', 'Patient', 'PaymentNotice', 'PaymentReconciliation', 'Person',
                 'PlanDefinition', 'Practitioner', 'PractitionerRole', 'Procedure', 'Provenance', 'Questionnaire',
                 'QuestionnaireResponse', 'RelatedPerson', 'RequestGroup', 'ResearchDefinition',
                 'ResearchElementDefinition', 'ResearchStudy', 'ResearchSubject', 'RiskAssessment',
                 'RiskEvidenceSynthesis', 'Schedule', 'SearchParameter', 'ServiceRequest', 'Slot', 'Specimen',
                 'SpecimenDefinition', 'StructureDefinition', 'StructureMap', 'Subscription', 'Substance',
                 'SubstanceSpecification', 'SupplyDelivery', 'SupplyRequest', 'Task',
                 'TerminologyCapabilities', 'TestReport', 'TestScript', 'ValueSet', 'VerificationResult',
                 'VisionPrescription']

    data_dir: Path = Path(__file__).parent.joinpath('./')

    collection_entries = {}
    config_entries = []

    for resource in resources:
        # first see if the folder exists
        resource_folder = data_dir.joinpath(resource.lower())
        if os.path.exists(resource_folder):
            shutil.rmtree(resource_folder)
        if not os.path.exists(resource_folder):
            print(f"Folder: {resource_folder} does not exist so creating it")
            # 1. create folder
            os.mkdir(resource_folder)
            # 2. create service file
            resource_file_name = resource_folder.joinpath(f"{resource.lower()}.service.js")
            service_code = f"""
// Autogenerated by generate_services.py. Do not edit.
const {{ COLLECTION }} = require('../../constants');
const base_service = require('../base/base.service');

const resource_name = '{resource}';
const collection_name = COLLECTION.{resource.upper()};

module.exports.search = (args, {{ req }}) =>
  base_service.search(args, {{ req }}, resource_name, collection_name);

module.exports.searchById = (args, {{ req }}) =>
  base_service.searchById(args, {{ req }}, resource_name, collection_name);

module.exports.create = (args, {{ req }}) =>
  base_service.create(args, {{ req }}, resource_name, collection_name);

module.exports.update = (args, {{ req }}) =>
  base_service.update(args, {{ req }}, resource_name, collection_name);

module.exports.merge = (args, {{ req }}) =>
  base_service.merge(args, {{ req }}, resource_name, collection_name);

module.exports.remove = (args, {{ req }}) =>
  base_service.remove(args, {{ req }}, resource_name, collection_name);

module.exports.searchByVersionId = (args, {{ req }}) =>
  base_service.search(args, {{ req }}, resource_name, collection_name);

module.exports.everything = (args, {{ req }}) =>
  base_service.everything(args, {{ req }}, resource_name, collection_name);

module.exports.history = (args, {{ req }}) =>
  base_service.history(args, {{ req }}, resource_name, collection_name);

module.exports.historyById = (args, {{ req }}) =>
  base_service.historyById(args, {{ req }}, resource_name, collection_name);

module.exports.patch = (args, {{ req }}) =>
  base_service.patch(args, {{ req }}, resource_name, collection_name);

module.exports.validate = (args, {{ req }}) =>
  base_service.validate(args, {{ req }}, resource_name, collection_name);
"""
            # 3. add config.js entry
            with open(resource_file_name, "w+") as file:
                print(f"Writing file: {resource_file_name}")
                file.write(service_code)
            collection_entries[resource.upper()] = resource
            config_entries.append(f"""
    {resource}: {{
      service: './src/services/{resource.lower()}/{resource.lower()}.service.js',
      versions: [VERSIONS['4_0_0']],
      operation: [
        {{
          name: 'everything',
          route: '/:id/$everything',
          method: 'GET',
          reference: 'https://www.hl7.org/fhir/patient-operation-everything.html',
        }},
        {{
          name: 'merge',
          route: '/:id/$merge',
          method: 'POST',
          reference: 'https://www.hl7.org/fhir/patient-operation-everything.html',
        }},
        {{
          name: 'merge',
          route: '/$merge',
          method: 'POST',
          reference: 'https://www.hl7.org/fhir/patient-operation-everything.html',
        }},
        {{
          name: 'validate',
          route: '/$validate',
          method: 'POST',
          reference: 'https://www.hl7.org/fhir/resource-operation-validate.html',
        }},
      ],
    }},""")
        else:
            print(f"Folder: {resource_folder} already exists")

    print("---- COLLECTION entries -----")
    for key, value in collection_entries.items():
        print("// Autogenerated by generate_services.py. Do not edit.")
        print(key + ":" + "'" + value + "'" + ",")
    print("---- Config entries -----")
    config_file_name = data_dir.joinpath(f"../profiles.js")
    with open(config_file_name, "w+") as file:
        file.write("const { VERSIONS } = require('@asymmetrik/node-fhir-server-core').constants;\n")
        file.write("// noinspection SpellCheckingInspection\n")
        file.write("const profiles = {\n")
        for config_entry in config_entries:
            print(config_entry)
            file.write(config_entry)
        file.write("""
};

module.exports = {
    profiles
};
""")

    return 0


if __name__ == "__main__":
    exit(main())
