// This code is generated by a code generator.  Do not edit.
/*eslint no-unused-vars: "off"*/
const {resolveType, findResourcesByReference, findResourceByReference, getResources} = require('../../common');

// noinspection JSUnusedLocalSymbols
module.exports = {
    RequestGroupActionParticipant: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    RequestGroupAction: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        participant: async (parent, args, context, info) => {
            return await findResourcesByReference(
                parent,
                args,
                context,
                info,
                parent.participant);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        resource: async (parent, args, context, info) => {
            return await findResourceByReference(
                parent,
                args,
                context,
                info,
                parent.resource);
        },
    }
};

