// This code is generated by a code generator.  Do not edit.
/*eslint no-unused-vars: "off"*/
const {resolveType, findResourcesByReference, findResourceByReference, getResources} = require('../../common');

// noinspection JSUnusedLocalSymbols
module.exports = {
    Query: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        coverageEligibilityResponse: async (parent, args, context, info) => {
            return await getResources(
                parent,
                args,
                context,
                info,
                'CoverageEligibilityResponse'
            );
        }
    },
    CoverageEligibilityResponseRequestor: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    CoverageEligibilityResponse: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        patient: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.patient);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        requestor: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.requestor);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        request: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.request);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        insurer: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.insurer);
        },
    }
};

