// This code is generated by a code generator.  Do not edit.
/*eslint no-unused-vars: "off"*/
const {resolveType, findResourcesByReference, findResourceByReference, getResources} = require('../../common');

// noinspection JSUnusedLocalSymbols
module.exports = {
    Query: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        deviceUseStatement: async (parent, args, context, info) => {
            return await getResources(
                parent,
                args,
                context,
                info,
                'DeviceUseStatement'
            );
        }
    },
    DeviceUseStatementSubject: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    DeviceUseStatementDerivedFrom: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    DeviceUseStatementSource: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    DeviceUseStatementReasonReference: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    DeviceUseStatement: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        basedOn: async (parent, args, context, info) => {
            return await findResourcesByReference(
                args,
                context,
                info,
                parent.basedOn);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        subject: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.subject);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        derivedFrom: async (parent, args, context, info) => {
            return await findResourcesByReference(
                args,
                context,
                info,
                parent.derivedFrom);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        source: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.source);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        device: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.device);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        reasonReference: async (parent, args, context, info) => {
            return await findResourcesByReference(
                args,
                context,
                info,
                parent.reasonReference);
        },
    }
};

