// This code is generated by a code generator.  Do not edit.
const {search} = require('../../../operations/search/search');
const {searchById} = require('../../../operations/searchById/searchById');
const {unBundle, resolveType, findResourcesByReference, findResourceByReference, getResources} = require('../../common');
const {NotFoundError} = require('../../../utils/httpErrors');

// noinspection JSUnusedLocalSymbols
module.exports = {
    Query: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        enrollmentResponse: async (parent, args, context, info) => {
            return await getResources(
                parent,
                args,
                context,
                info,
                'EnrollmentResponse'
            );
        }
    },
    EnrollmentResponseRequestProvider: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    EnrollmentResponse: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        request: async (parent, args, context, info) => {
            return await findResourceByReference(parent.request);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        organization: async (parent, args, context, info) => {
            return await findResourceByReference(parent.organization);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        requestProvider: async (parent, args, context, info) => {
            return await findResourceByReference(parent.requestProvider);
        },
    }
};

