// This code is generated by a code generator.  Do not edit.
/*eslint no-unused-vars: "off"*/
const {resolveType, findResourcesByReference, findResourceByReference, getResources} = require('../../common');

// noinspection JSUnusedLocalSymbols
module.exports = {
    Query: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        imagingStudy: async (parent, args, context, info) => {
            return await getResources(
                parent,
                args,
                context,
                info,
                'ImagingStudy'
            );
        }
    },
    ImagingStudySubject: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    ImagingStudyBasedOn: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    ImagingStudyReferrer: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    ImagingStudyInterpreter: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    ImagingStudyReasonReference: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    ImagingStudy: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        subject: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.subject);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        encounter: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.encounter);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        basedOn: async (parent, args, context, info) => {
            return await findResourcesByReference(
                args,
                context,
                info,
                parent.basedOn);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        referrer: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.referrer);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        interpreter: async (parent, args, context, info) => {
            return await findResourcesByReference(
                args,
                context,
                info,
                parent.interpreter);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        endpoint: async (parent, args, context, info) => {
            return await findResourcesByReference(
                args,
                context,
                info,
                parent.endpoint);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        procedureReference: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.procedureReference);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        location: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.location);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        reasonReference: async (parent, args, context, info) => {
            return await findResourcesByReference(
                args,
                context,
                info,
                parent.reasonReference);
        },
    }
};

