// This code is generated by a code generator.  Do not edit.
const {search} = require('../../../operations/search/search');
const {searchById} = require('../../../operations/searchById/searchById');
const {unBundle, resolveType, findResourcesByReference, findResourceByReference, getResources} = require('../../common');
const {NotFoundError} = require('../../../utils/httpErrors');

// noinspection JSUnusedLocalSymbols
module.exports = {
    Query: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        researchSubject: async (parent, args, context, info) => {
            return await getResources(
                parent,
                args,
                context,
                info,
                'ResearchSubject'
            );
        }
    },
    ResearchSubject: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        study: async (parent, args, context, info) => {
            return await findResourceByReference(parent.study);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        individual: async (parent, args, context, info) => {
            return await findResourceByReference(parent.individual);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        consent: async (parent, args, context, info) => {
            return await findResourceByReference(parent.consent);
        },
    }
};

