// This code is generated by a code generator.  Do not edit.
const {resolveType, findResourcesByReference, findResourceByReference, getResources} = require('../../common');

// noinspection JSUnusedLocalSymbols
module.exports = {
    Query: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        researchElementDefinition: async (parent, args, context, info) => {
            return await getResources(
                parent,
                args,
                context,
                info,
                'ResearchElementDefinition'
            );
        }
    },
    ResearchElementDefinition: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        subjectReference: async (parent, args, context, info) => {
            return await findResourceByReference(parent.subjectReference);
        },
    }
};

