// This code is generated by a code generator.  Do not edit.
/*eslint no-unused-vars: "off"*/
const {resolveType, findResourcesByReference, findResourceByReference, getResources} = require('../../common');

// noinspection JSUnusedLocalSymbols
module.exports = {
    Query: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        visionPrescription: async (parent, args, context, info) => {
            return await getResources(
                parent,
                args,
                context,
                info,
                'VisionPrescription'
            );
        }
    },
    VisionPrescriptionPrescriber: {
        __resolveType(obj, context, info) {
            return resolveType(obj, context, info);
        },
    },
    VisionPrescription: {
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        patient: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.patient);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        encounter: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.encounter);
        },
        // noinspection JSUnusedLocalSymbols
        // eslint-disable-next-line no-unused-vars
        prescriber: async (parent, args, context, info) => {
            return await findResourceByReference(
                args,
                context,
                info,
                parent.prescriber);
        },
    }
};

